services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    buildCommand: ""
    startCommand: ""   # Render usar√° ENTRYPOINT
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

      # Google Calendar
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false   # JSON en Base64

      # Database (Postgres)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: smile-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: smile-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: smile-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: smile-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: smile-db
          property: password

databases:
  - name: smile-db
    plan: free
    region: oregon
